trigger:
  branches:
    include:
      - refs/tags/*

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: maven

steps:
- task: Gradle@2
  displayName: 'Gradle Maven Publish'
  inputs:
    gradleWrapperFile: '$(Build.SourcesDirectory)/gradlew'
    options: '--no-daemon -Dbuild.sourcebranch=$(Build.SourceBranch) -Dgithub.repy.token=$(github.repy.token)'
    workingDirectory: '$(Build.SourcesDirectory)'
    tasks: 'publish'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
